[package]
name = "util-types"
description = "Utilitarian types for contracts"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }

[dependencies]
cosmwasm-std = { workspace = true }
cw-storage-plus = { workspace = true }
serde = { workspace = true }
cosmwasm-schema = { workspace = true }
thiserror = { workspace = true }
