[package]
name = "cw-paginate"
version = { workspace = true }
edition = { workspace = true }
authors = ["not me, it is from boss ekez ekez@withoutdoing.com"]
description = "A package for paginating cosmwasm maps."

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-storage = { workspace = true }
cw-storage-plus = { workspace = true }
serde = { workspace = true, default-features = false }
